name: push-workflow
on: push

jobs:
  push-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions edit
