name: var-1
on: push

env:
  level: workflow

jobs:
  get-env-1:
    runs-on: ubuntu-latest
    steps:
      - name: check env
        run: echo "LEVEL ${{ env.level }}"

  get-env-2:
    runs-on: ubuntu-latest
    env:
      level: job
    steps:
      - name: check env
        run: echo "LEVEL ${{ env.level }}"

  get-env-3:
    runs-on: ubuntu-latest
    steps:
      - name: check env
        env:
          level: step
        run: echo "LEVEL ${{ env.level }}"

  get-env-4:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: |
          echo "level=run" >> $GITHUB_ENV
      - name: check env
        run: echo "LEVEL ${{ env.level }}"
