name: issue-workflow
on:
  issues:
    types:
      - opened

jobs:
  issue-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions