name: path-filter
on:
  push:
    paths:
      - '!.github/workflows/part1/push.yaml'
      - '.github/workflows/part1/*'

jobs:
  branch-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo world