name: pr-workflow
on: pull_request

jobs:
  pr-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions