name: timeout
on:
  push:

jobs:
  tag-filter:
    runs-on: ubuntu-latest
    steps:
      - name: loop
        run: |
          count=0
          while true; do
            echo "seconds: $count"
            count=$((count+1))
            sleep 1
          done
      - name: echo
        run: echo world